name: Python Unit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python

    - name: List files for debugging
      run: ls -R

    - name: Run Unit Tests
      run: |
        export PYTHONPATH=$(pwd)/src/app/backend
        python -m unittest discover -s tests